## PyTorch Basics

- Basic Tensor Operations
- Autograd
- Training loop with model, loss & optimizer
- Neural Network
- GPU support
- Working of custom Datasets and Dataloaders


### Basic Tensor Operations

In [1]:
import torch
torch.empty(1)

tensor([0.])

In [2]:
torch.empty([2,3,4])

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [3]:
y = torch.rand([3,4,5])
y

tensor([[[0.8890, 0.2945, 0.4910, 0.7526, 0.5299],
         [0.6002, 0.0156, 0.8237, 0.2810, 0.2004],
         [0.9030, 0.2810, 0.7067, 0.0748, 0.9059],
         [0.9844, 0.9314, 0.1575, 0.9912, 0.0809]],

        [[0.9847, 0.8644, 0.0481, 0.7922, 0.8131],
         [0.8574, 0.3858, 0.6432, 0.2940, 0.0903],
         [0.1011, 0.9237, 0.2300, 0.7564, 0.1402],
         [0.1552, 0.4634, 0.9890, 0.0916, 0.3709]],

        [[0.0650, 0.5188, 0.8187, 0.8345, 0.3984],
         [0.8679, 0.3188, 0.2989, 0.0860, 0.5621],
         [0.4283, 0.9941, 0.3105, 0.2222, 0.0237],
         [0.3597, 0.2994, 0.3429, 0.9960, 0.2089]]])

In [4]:
y.size()

torch.Size([3, 4, 5])

In [5]:
y.dtype

torch.float32

In [10]:
x = torch.rand([2,3])
y = torch.rand([2,3])
z = x + y
z

tensor([[1.5118, 0.4861, 0.2198],
        [0.5628, 0.9093, 0.3365]])

In [11]:
# inplace operation
y.add_(x)

tensor([[1.5118, 0.4861, 0.2198],
        [0.5628, 0.9093, 0.3365]])

In [13]:

x= torch.rand([3,4])
x

tensor([[0.4656, 0.1826, 0.3996, 0.7463],
        [0.1164, 0.4148, 0.1755, 0.5546],
        [0.1678, 0.6080, 0.6579, 0.8241]])

In [14]:
#reshape
x.view(12)

tensor([0.4656, 0.1826, 0.3996, 0.7463, 0.1164, 0.4148, 0.1755, 0.5546, 0.1678,
        0.6080, 0.6579, 0.8241])

In [15]:
x.view(-1,6)

tensor([[0.4656, 0.1826, 0.3996, 0.7463, 0.1164, 0.4148],
        [0.1755, 0.5546, 0.1678, 0.6080, 0.6579, 0.8241]])

## GPU Support

In [ ]:
device = torch.device('mps' if torch.backends.mps.is_available()  else 'cpu')
print(device)

In [ ]:
y = torch.rand([3,4,5])
y = y.to(device)
y

In [ ]:
y.to('cpu')

In [17]:
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader


In [ ]:
class PlayCardDataset(Dataset):
    def __init__(self, data_dir,transform=None):
        pass

    def __len__(self):
        pass

    def __getitem__(self, idx):
        return